function done(){
    console.log("done");
}
function done1(){
    console.log(age);
    let age=10;
}

function error(){
    throw new Error("Error here");
}

var promise=new Promise((resolve,reject)=>{
    resolve();
    reject();
});
promise.then(done).catch(error);
promise.then(done1).catch(error);


//throwing error 


function done(){
    console.log(age);
    let age;
 }
 function error(){
     throw new Error("error found")
 }

 var promise=new Promise((resolve,reject)=>{
     resolve();
     reject();
 });
 
 promise.then(done).catch(error);
